/* ==========================================================================
   AURELIA — Haute Roastery & Coffee Sanctuary
   Curated Menu Catalog & Sensory Profiler Data (18 Unique Creations)
   ========================================================================== */

export const MENU_ITEMS = [
  // --- 1. SIGNATURE ESPRESSO CREATIONS (4 UNIQUE ITEMS) ---
  {
    id: "sig-01",
    name: "Aurelia 24K Gold Leaf Cortado",
    category: "signature",
    categoryName: "Signature Espressos",
    subtitle: "Ristretto • Madagascar Vanilla • Edible 24K Gold",
    price: 14.50,
    badge: "Sanctuary Icon",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=85",
    description: "Double extraction of our private reserve Ethiopian Geisha, folded with steamed jersey milk infused with Tahitian vanilla bean, crowned with delicate 24-karat Florentine gold leaf.",
    origin: "Gesha Village, Bench Maji, Ethiopia",
    altitude: "2,050m AMSL",
    process: "Natural Anaerobic Fermentation",
    roastLevel: "Medium-Light Velvet",
    tastingNotes: ["Bergamot Blossom", "Wild Honey", "Golden Plum", "Velvet Cocoa"],
    metrics: { acidity: 78, body: 82, sweetness: 90, aroma: 96 },
    pairing: "Sicilian Pistachio & Raspberry Tart"
  },
  {
    id: "sig-02",
    name: "Velvet Obsidian Espresso",
    category: "signature",
    categoryName: "Signature Espressos",
    subtitle: "Double Shot Extraction • Crema Densa",
    price: 8.50,
    badge: "Master Roaster Choice",
    image: "https://images.unsplash.com/photo-1510688773642-f74d8a4a0a71?auto=format&fit=crop&w=1000&q=85",
    description: "Extracted at precisely 9.2 bars with 93.5°C volcanic mineral water. Yields an unctuous, thick tiger-striped crema with profound dark chocolate and toasted hazelnut depth.",
    origin: "Antigua Valley, Guatemala",
    altitude: "1,850m AMSL",
    process: "Fully Washed & Sun Dried",
    roastLevel: "Espresso Roast",
    tastingNotes: ["85% Venezuelan Cacao", "Roasted Hazelnut", "Black Cherry", "Brown Sugar Crema"],
    metrics: { acidity: 55, body: 94, sweetness: 72, aroma: 88 },
    pairing: "Bordeaux Madagascar Vanilla Canelé"
  },
  {
    id: "sig-03",
    name: "Saffron & Orange Blossom Flat White",
    category: "signature",
    categoryName: "Signature Espressos",
    subtitle: "Persian Saffron • Blossom Mist • Micro-foam",
    price: 12.00,
    badge: "Seasonal Creation",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=85",
    description: "A velvety micro-foam flat white steeped with pure Persian saffron threads and organic orange blossom hydrosol, finished with finely ground crushed Iranian pistachios.",
    origin: "Huila, Colombia",
    altitude: "1,900m AMSL",
    process: "Washed Honey Process",
    roastLevel: "Medium Silk",
    tastingNotes: ["Floral Saffron", "Candied Mandarin", "Almond Paste", "Dulce de Leche"],
    metrics: { acidity: 68, body: 86, sweetness: 85, aroma: 94 },
    pairing: "Pure Butter French Croissant au Beurre"
  },
  {
    id: "sig-04",
    name: "Smoked Oak & Maple Macchiato",
    category: "signature",
    categoryName: "Signature Espressos",
    subtitle: "Applewood Smoke • Aged Vermont Maple",
    price: 11.50,
    badge: "Barista Special",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=85",
    description: "Served under a glass bell jar captured with fragrant applewood smoke. Double ristretto kissed with aged bourbon-barrel maple syrup and a spoon of dense velvety froth.",
    origin: "Cerrado Mineiro, Brazil",
    altitude: "1,200m AMSL",
    process: "Pulped Natural",
    roastLevel: "Medium-Dark",
    tastingNotes: ["Smoked Cedar", "Bourbon Vanilla", "Toffee", "Dark Molasses"],
    metrics: { acidity: 45, body: 90, sweetness: 88, aroma: 92 },
    pairing: "Bordeaux Madagascar Vanilla Canelé"
  },

  // --- 2. SINGLE-ORIGIN POUR-OVERS & SIPHONS (4 UNIQUE ITEMS) ---
  {
    id: "po-01",
    name: "Panama Hacienda La Esmeralda Geisha",
    category: "pourover",
    categoryName: "Single-Origin Pour-Overs",
    subtitle: "V60 Copper Ritual • Lot #07 Micro-Harvest",
    price: 19.00,
    badge: "Rare Grand Cru",
    image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=1000&q=85",
    description: "The crown jewel of world coffee. Brewed hand-poured through hand-hammered copper drippers at 91°C. Extraordinary clarity, silky tea-like body, and luminous floral vibrancy.",
    origin: "Boquete, Chiriquí, Panama",
    altitude: "1,800m AMSL",
    process: "Slow Dry Natural",
    roastLevel: "Light Cinnamon",
    tastingNotes: ["White Jasmine", "Meyer Lemon", "White Peach", "Papaya Nectar"],
    metrics: { acidity: 95, body: 62, sweetness: 92, aroma: 99 },
    pairing: "Sicilian Pistachio & Raspberry Tart"
  },
  {
    id: "po-02",
    name: "Aurelia Royal Halogen Siphon Geisha",
    category: "pourover",
    categoryName: "Single-Origin Pour-Overs",
    subtitle: "Japanese Vacuum Siphon • Halogen Beam Chamber",
    price: 22.00,
    badge: "Theatrical Ritual",
    image: "https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?auto=format&fit=crop&w=1000&q=85",
    description: "Brewed live tableside using a gold-accented twin-globe vacuum glass siphon heated by an ambient halogen beam. Delivers unmatched aromatic amplification and pristine velvet clarity.",
    origin: "Volcán Barú, Boquete, Panama",
    altitude: "1,920m AMSL",
    process: "Anaerobic Slow Natural",
    roastLevel: "Light Scandinavian",
    tastingNotes: ["Orange Blossom", "Bergamot Liqueur", "Golden Kiwi", "Elderflower"],
    metrics: { acidity: 92, body: 74, sweetness: 95, aroma: 100 },
    pairing: "Pure Butter French Croissant au Beurre"
  },
  {
    id: "po-03",
    name: "Ethiopia Yirgacheffe Aricha Heirloom",
    category: "pourover",
    categoryName: "Single-Origin Pour-Overs",
    subtitle: "Origami Dripper • Wild Forest Varietals",
    price: 13.00,
    badge: "Top Seller",
    image: "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=1000&q=85",
    description: "Indigenous wild heirloom varietals grown shaded beneath canopies of eucalyptus trees. Bursting with explosive aromatics of lavender and candied blueberry preserves.",
    origin: "Gedeo Zone, Yirgacheffe, Ethiopia",
    altitude: "2,100m AMSL",
    process: "Anaerobic Natural",
    roastLevel: "Light-Medium",
    tastingNotes: ["Ripe Blueberry", "Lavender Earl Grey", "Apricot Jam", "Cane Sugar"],
    metrics: { acidity: 88, body: 70, sweetness: 89, aroma: 95 },
    pairing: "Bordeaux Madagascar Vanilla Canelé"
  },
  {
    id: "po-04",
    name: "Colombia Pink Bourbon San Adolfo",
    category: "pourover",
    categoryName: "Single-Origin Pour-Overs",
    subtitle: "Kalita Wave 185 • Thermal Shock Wash",
    price: 15.00,
    badge: "Microlot",
    image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=1000&q=85",
    description: "A rare natural mutation boasting pink-blushed cherries. Thermal shock washed to lock in intense sweetness, pink guava highlights, and a lingering honeysuckle finish.",
    origin: "San Adolfo, Acevedo, Huila",
    altitude: "1,750m AMSL",
    process: "Thermal Shock Washed",
    roastLevel: "Light",
    tastingNotes: ["Pink Guava", "Red Currant", "Honeysuckle", "Champagne Sparkle"],
    metrics: { acidity: 91, body: 68, sweetness: 94, aroma: 93 },
    pairing: "Sicilian Pistachio & Raspberry Tart"
  },

  // --- 3. COLD INFUSIONS & NITRO EXTRACTIONS (4 UNIQUE ITEMS) ---
  {
    id: "cold-01",
    name: "Affogato al Caffè Riserva",
    category: "cold",
    categoryName: "Cold Infusions & Nitro",
    subtitle: "Gelato Artigianale • Single Origin Ristretto • Amaretti",
    price: 12.00,
    badge: "Italian Masterpiece",
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=1000&q=85",
    description: "Handcrafted Tahitian vanilla bean gelato churned in small batches, bathed tableside in a piping double shot of Guatemalan Antigua ristretto. Garnished with crushed Sardinian amaretti crumble.",
    origin: "Florence & Antigua Blend",
    altitude: "Artisan Gelato Atelier",
    process: "Gelato & Ristretto Harmony",
    roastLevel: "Full Crema Extraction",
    tastingNotes: ["Warm Espresso", "Cold Vanilla Custard", "Almond Marzipan", "Dark Chocolate Shavings"],
    metrics: { acidity: 50, body: 96, sweetness: 92, aroma: 94 },
    pairing: "Pure Butter French Croissant au Beurre"
  },
  {
    id: "cold-02",
    name: "Kyoto 18-Hour Tower Cold Drip",
    category: "cold",
    categoryName: "Cold Infusions & Nitro",
    subtitle: "Single-Drop Glacial Extraction • Hand-Carved Ice",
    price: 13.50,
    badge: "Artisanal Extraction",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1000&q=85",
    description: "Extracted drop-by-drop through towering hand-blown Japanese glass distillation columns over 18 hours. Ultra-clean, liqueur-like mouthfeel, served over a crystal hand-carved ice sphere.",
    origin: "Tarrazú, Costa Rica",
    altitude: "1,900m AMSL",
    process: "White Honey Process",
    roastLevel: "Light Medium",
    tastingNotes: ["Cognac Notes", "Dark Cherry Glaze", "Roasted Cacao Nibs", "Silky Vanilla"],
    metrics: { acidity: 64, body: 88, sweetness: 86, aroma: 92 },
    pairing: "Bordeaux Madagascar Vanilla Canelé"
  },
  {
    id: "cold-03",
    name: "Amalfi Cold Brew Tonic al Limone",
    category: "cold",
    categoryName: "Cold Infusions & Nitro",
    subtitle: "Fever-Tree Tonic • Charred Amalfi Lemon • Cold Extraction",
    price: 11.00,
    badge: "Summer Refreshment",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=1000&q=85",
    description: "Slow-dripped Ethiopian heirloom coffee layered gracefully over botanical elderflower tonic and artisan crystalline ice, garnished with charred Amalfi lemon rind and fresh garden thyme.",
    origin: "Sidama, Ethiopia",
    altitude: "1,950m AMSL",
    process: "Cold Drip Infusion",
    roastLevel: "Light Roast",
    tastingNotes: ["Citrus Zest", "Elderflower", "Sparkling Quinine", "Jasmine Bloom"],
    metrics: { acidity: 86, body: 54, sweetness: 82, aroma: 93 },
    pairing: "Sicilian Pistachio & Raspberry Tart"
  },
  {
    id: "cold-04",
    name: "Velvet Nitro Cold Brew Stout",
    category: "cold",
    categoryName: "Cold Infusions & Nitro",
    subtitle: "Guinness-Style Cascade Head • Nitro Infusion",
    price: 11.00,
    badge: "Staff Favorite",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1000&q=85",
    description: "Cold brewed for 24 hours under inert nitrogen gas. Pours with a mesmerizing cascading head of micro-bubbles, yielding a creamy, stout-like sweetness without a drop of dairy.",
    origin: "Antioquia, Colombia",
    altitude: "1,800m AMSL",
    process: "Extended Maceration",
    roastLevel: "Medium-Dark",
    tastingNotes: ["Creamy Cocoa", "Toasted Oats", "Molasses Sweetness", "Espresso Crema"],
    metrics: { acidity: 40, body: 95, sweetness: 84, aroma: 87 },
    pairing: "Pure Butter French Croissant au Beurre"
  },

  // --- 4. HAUTE BOTANICALS & VELVET LATTES (3 UNIQUE ITEMS) ---
  {
    id: "bot-01",
    name: "Uji Ceremonial Matcha & White Chocolate",
    category: "botanical",
    categoryName: "Haute Botanicals & Lattes",
    subtitle: "First Harvest Kyoto Matcha • Valrhona Ivoire",
    price: 12.50,
    badge: "Japanese Imperial",
    image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=1000&q=85",
    description: "Whisked stone-ground ceremonial matcha sourced directly from Uji, Kyoto. Combined with melted Valrhona 35% Ivoire white chocolate and steamed organic oat milk.",
    origin: "Uji, Kyoto, Japan",
    altitude: "Shaded Green Tea Plantation",
    process: "Stone Ground First Flush Tencha",
    roastLevel: "Ceremonial Grade",
    tastingNotes: ["Sweet Umami", "Spring Grass", "Melted White Chocolate", "Creamy Vanilla"],
    metrics: { acidity: 20, body: 90, sweetness: 92, aroma: 95 },
    pairing: "Bordeaux Madagascar Vanilla Canelé"
  },
  {
    id: "bot-02",
    name: "Cardamom Rose Damascena Latte",
    category: "botanical",
    categoryName: "Haute Botanicals & Lattes",
    subtitle: "Steam-Distilled Rosewater • Green Cardamom Pods",
    price: 11.50,
    badge: "Sensory Elixir",
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=1000&q=85",
    description: "An intoxicating harmony of crushed green cardamom pods, pure Lebanese Damascus rose water, double espresso, and silk-textured milk, adorned with dried organic rose petals.",
    origin: "Sidama, Ethiopia",
    altitude: "2,000m AMSL",
    process: "Natural Process",
    roastLevel: "Medium",
    tastingNotes: ["Damascus Rose", "Spiced Cardamom", "Cinnamon Bark", "Honey Crema"],
    metrics: { acidity: 50, body: 85, sweetness: 88, aroma: 98 },
    pairing: "Sicilian Pistachio & Raspberry Tart"
  },
  {
    id: "bot-03",
    name: "Golden Turmeric & Wild Blossom Elixir",
    category: "botanical",
    categoryName: "Haute Botanicals & Lattes",
    subtitle: "Raw Alleppey Turmeric • Fresh Ginger Root • Oat Cream",
    price: 11.00,
    badge: "Ayurvedic Gold",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1000&q=85",
    description: "Sun-dried Kerala turmeric cold-pressed with baby ginger, black pepper extract for enhanced bioavailability, and steamed organic oat milk, crowned with wildflower honey.",
    origin: "Alleppey, Kerala, India",
    altitude: "Coastal Foothills",
    process: "Sun-Cured Roots",
    roastLevel: "Raw Spiced Infusion",
    tastingNotes: ["Earthy Turmeric", "Zesty Ginger", "Velvet Oat Cream", "Wild Blossom Honey"],
    metrics: { acidity: 25, body: 88, sweetness: 86, aroma: 96 },
    pairing: "Pure Butter French Croissant au Beurre"
  },

  // --- 5. ARTISANAL FRENCH PÂTISSERIE (3 UNIQUE ITEMS) ---
  {
    id: "pat-01",
    name: "Pure Butter French Croissant au Beurre",
    category: "patisserie",
    categoryName: "Artisanal Pâtisserie",
    subtitle: "AOP Charentes-Poitou Butter • 72-Hour Fermentation",
    price: 6.50,
    badge: "Fresh Daily at 7 AM",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1000&q=85",
    description: "Laminated with 84% fat AOP Normandy butter across 27 delicate golden layers. Shatteringly crisp honeycomb exterior revealing an airy, cloud-soft buttery crumb.",
    origin: "Sanctuary Bakehouse (Baked Fresh Twice Daily)",
    altitude: "French Atelier Oven",
    process: "Slow 72-Hour Sourdough Poolish",
    roastLevel: "Golden Caramelized Crust",
    tastingNotes: ["Cultured Sweet Cream Butter", "Caramelized Wheat", "Flaky Sea Salt"],
    metrics: { acidity: 15, body: 85, sweetness: 65, aroma: 92 },
    pairing: "Velvet Obsidian Espresso"
  },
  {
    id: "pat-02",
    name: "Bordeaux Madagascar Vanilla Canelé",
    category: "patisserie",
    categoryName: "Artisanal Pâtisserie",
    subtitle: "Beeswax-Lined Copper Molds • Dark Rum Infusion",
    price: 5.50,
    badge: "Classic Bordeaux",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=85",
    description: "Baked in traditional beeswax-lined French copper molds. Deep caramelized mahogany crust enclosing a soft, custardy center infused with Martinique dark rum and Bourbon vanilla.",
    origin: "Bordeaux Heritage Recipe",
    altitude: "Sanctuary Copper Mold Oven",
    process: "24-Hour Cold Batter Rest",
    roastLevel: "Dark Mahogany Caramelization",
    tastingNotes: ["Dark Molasses Crust", "Vanilla Bean Custard", "Aged Rum Warmth"],
    metrics: { acidity: 10, body: 92, sweetness: 86, aroma: 95 },
    pairing: "Aurelia 24K Gold Leaf Cortado"
  },
  {
    id: "pat-03",
    name: "Sicilian Pistachio & Raspberry Tart",
    category: "patisserie",
    categoryName: "Artisanal Pâtisserie",
    subtitle: "Bronte Pistachio Praline • Wild Raspberry Coulis",
    price: 9.50,
    badge: "Chef's Signature",
    image: "https://images.unsplash.com/photo-1579888944880-d98341245702?auto=format&fit=crop&w=1000&q=85",
    description: "Pâte sablée tart shell filled with whipped Sicilian Bronte pistachio ganache, layered with fresh tart organic raspberries, and finished with crushed emerald pistachios.",
    origin: "Bronte, Sicily & Brittany Cream",
    altitude: "Sanctuary Pastry Studio",
    process: "Small Batch Pastry Atelier",
    roastLevel: "Freshly Assembled Daily",
    tastingNotes: ["Nutty Bronte Pistachio", "Tart Wild Raspberry", "Flaky Butter Sablée", "White Velvet Cream"],
    metrics: { acidity: 65, body: 80, sweetness: 85, aroma: 93 },
    pairing: "Panama Hacienda La Esmeralda Geisha"
  }
];

export const CUPPING_FLIGHT_LOTS = [
  {
    id: "flight-geisha",
    name: "Panama Esmeralda Geisha",
    terroir: "Boquete • 1,800m",
    profile: "White Jasmine, Bergamot & Honey",
    badge: "Floral Elegance",
    selected: true
  },
  {
    id: "flight-yirgacheffe",
    name: "Ethiopian Aricha Heirloom",
    terroir: "Yirgacheffe • 2,100m",
    profile: "Candied Blueberry & Lavender",
    badge: "Fruity Bloom",
    selected: true
  },
  {
    id: "flight-bourbon",
    name: "Colombia Pink Bourbon",
    terroir: "Huila • 1,750m",
    profile: "Pink Guava & Champagne Sweetness",
    badge: "Rare Mutation",
    selected: true
  },
  {
    id: "flight-kerinci",
    name: "Sumatra Kerinci Volcano",
    terroir: "Mount Kerinci • 1,600m",
    profile: "Dark Honey, Cedar & Cacao",
    badge: "Deep Earthy",
    selected: false
  },
  {
    id: "flight-antigua",
    name: "Guatemala Antigua Obsidian",
    terroir: "Antigua Valley • 1,850m",
    profile: "85% Cacao & Hazelnut Crema",
    badge: "Dark Chocolate",
    selected: false
  }
];
